
# Admin
set $dbus_env dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
set $key_rng gnome-keyring-daemon --start --components=secrets
set $su_auth /usr/lib/polkit-kde-authentication-agent-1



# Scripts
set $battery_script $config_root/scripts/battery_notification.sh



# Waybar
exec waybar -c $config_root/waybar/sway/waybar_sway.jsonc -s $config_root/waybar/sway/style.css &


# Themeing
set $su_cursor swaymsg seat seat0 cursor set Adwaita 10
set $gnome_buttons gsettings set org.gnome.desktop.wm.preferences button-layout :
set $su_bg swaybg -i $config_root/hypr/backgroundFish.jpg -m fill

# Execute
exec $dbus_env & $key_rng & $su_auth
exec $su_cursor & $gnome_buttons & $su_bg
exec $battery_script
