
set $workspace_script $config_root/sway/sway_scripts/sway-workspace/target/release/sway-workspace

# Show info bar
bindgesture swipe:3:down exec killall -SIGUSR1 waybar
bindgesture swipe:3:up exec killall -SIGUSR1 waybar


# Move workspaces
# Direction swapped for swiping
bindgesture swipe:4:right exec $workspace_script move left
bindgesture swipe:4:left exec $workspace_script move right
bindsym $mod+$alt+right exec $workspace_script move right
bindsym $mod+$alt+left exec $workspace_script move left
bindsym $mod+$alt+d exec $workspace_script move right
bindsym $mod+$alt+a exec $workspace_script move left


# Create new workspaces
bindsym $mod+ctrl+right exec $workspace_script create right
bindsym $mod+ctrl+left exec $workspace_script create left
bindsym $mod+ctrl+d exec $workspace_script create right
bindsym $mod+ctrl+a exec $workspace_script create left


# Move focused container to another workspace
bindsym $mod+$alt+shift+right exec $workspace_script move_focused right
bindsym $mod+$alt+shift+left exec $workspace_script move_focused left
bindsym $mod+$alt+shift+d exec $workspace_script move_focused right
bindsym $mod+$alt+shift+a exec $workspace_script move_focused left


# Move focused container to new workspace
bindsym $mod+ctrl+shift+right exec $workspace_script move_focused_new right
bindsym $mod+ctrl+shift+left exec $workspace_script move_focused_new left
bindsym $mod+ctrl+shift+d exec $workspace_script move_focused_new right
bindsym $mod+ctrl+shift+a exec $workspace_script move_focused_new left


# Move focus
bindsym $mod+up focus up
bindsym $mod+down focus down
bindsym $mod+left focus left
bindsym $mod+right focus right

# Move focused container
bindsym $mod+shift+up move up
bindsym $mod+shift+down move down
bindsym $mod+shift+left move left
bindsym $mod+shift+right move right
