
# Admin
set $dbus_env dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SWAYSOCK
set $xdg_desktop_portal systemctl --user restart xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-gtk
set $key_rng gnome-keyring-daemon --start --components=secrets
set $su_auth /usr/lib/polkit-kde-authentication-agent-1



# Scripts
set $battery_script $config_root/scripts/battery_notification.sh



# Waybar
set $waybar waybar -c $config_root/waybar/sway/waybar_sway.jsonc -s $config_root/waybar/sway/style.css



# Themeing
set $su_cursor swaymsg seat seat0 cursor set Adwaita 10
set $gnome_buttons gsettings set org.gnome.desktop.wm.preferences button-layout :
set $background swaybg -i ~/Documents/Config/Dotfiles/src/hypr/backgroundFish.jpg -m fill



# Clipboard
set $su_clip_txt wl-paste --type text --watch cliphist store
set $su_clip_img wl-paste --type image --watch cliphist store



# Execute
exec $background &
exec_always $dbus_env & $xdg_desktop_portal &
exec $key_rng & $su_auth &

exec $waybar &
exec $su_cursor & $gnome_buttons &
exec $battery_script &
exec $su_clip_txt & $su_clip_img &
