# Keybinds for opening apps
# Try to use no additional mod key as a rule

# Open apps
# bind = $mainMod, Q, exec, kitty          # terminal, in main conf file
# bind = $mainMod, W, exec,
bind = $mainMod, E, exec, nemo         # file browser
bind = $mainMod, R, exec, wofi -i --show drun # runner
# bind = $mainMod, T, exec,
# bind = $mainMod, Y, exec,
# bind = $mainMod, U, exec,
# bind = $mainMod, I, exec,
# bind = $mainMod, O, exec,
# bind = $mainMod, P, exec,

# homerow left
bind = $mainMod, A, exec, code
bind = $mainMod, S, exec, firefox
bind = $mainMod, D, exec, qalculate-gtk
# bind = $mainMod, F, exec, 


# Firefox bookmarks, homerow right
# bind = $mainMod, G, exec, firefox
# bind = $mainMod, H, exec, firefox
# bind = $mainMod, j, exec, firefox
# bind = $mainMod, K, exec, firefox
# bind = $mainMod, L, exec, firefox
