# Keysbindings that act on workspaces, not windows
# Try to use $tertiary as a rule

$create_workspace = python ~/.config/hypr/createWorkspace.py

# Switch workspaces with mainMod + [0-9]
# bind = $mainMod, 1, workspace, 112
# bind = $mainMod, 2, workspace, 2
# bind = $mainMod, 3, workspace, 3
# bind = $mainMod, 4, workspace, 4
# bind = $mainMod, 5, workspace, 5
# bind = $mainMod, 6, workspace, 6
# bind = $mainMod, 7, workspace, 7
# bind = $mainMod, 8, workspace, 8
# bind = $mainMod, 9, workspace, 9
# bind = $mainMod, 0, workspace, 10

# Switch to adjacent workspace
bind = $mainMod $tertiary, RIGHT, workspace, e+1
bind = $mainMod $tertiary, LEFT , workspace, e-1

bind = $mainMod Control_L, RIGHT, exec, $create_workspace 1
bind = $mainMod Control_L, LEFT , exec, $create_workspace 0

gesture = 4, right, dispatcher, workspace, e-1
gesture = 4, left, dispatcher, workspace, e+1

# gesture = 4, right, workspace, e+1
# gesture = 4, left, workspace, e+1
